gems: [jekyll-paginate]

# Site settings

name: Vault 47
email: qubit47@gmail.com
author: Billy Qi
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/Qibit47/
baseurl: ""
description: Notes for Everything
meta_description: Billy Qi;Personal Blog;
motto: Notes for Everything
banner: No hurt fellings.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: Qibit47
highlighter: rouge

# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A vault built for articles by Billy Qi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  Qibit47

# Build settings
markdown: kramdown

# FB:
  # comments :
    # provider : duoshuo
    # duoshuo:
        # short_name : luoyan35714
    # disqus :
        # short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
